### ISSUE TITLE
files access not working

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/brc_oodapps#12]
Two SN tickets, and I've confirmed the same behavior under my account.

INC1225732
INC1223868

**Comment by markyashar** [comment]
When I tried this today, I get the error message (at the url: https://ood.brc.berkeley.edu/pun/sys/files/fs/global/home/users/myashar)

"We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

Technical details for the administrator of this website"

**Comment by paciorek** [comment]
@tin6150 @wfeinstein it looks like this is still a problem sometimes - I just got it to work some of the time, but it also failed some of the time. Any thoughts on how to debug? This is rather out of my ability to troubleshoot. 

Would be nice it it were working consistently for the Python/Jupyter training Nov. 15.

@jpdunc23, just an FYI.

**Comment by tin6150** [comment]
FYI: I looked at the two tickets and they don't seems to be an ood config/code issue.  So, response will be tracked in the service now tickets rather than here, unless we discover code change is needed.

**Comment by paciorek** [comment]
Notes from a Slack exchange between Tin and John:


￼￼
tin￼  2:00 PM
i guess we will need a much beefier ood.brc vm ￼
**^ tin ood.brc.berkeley.edu ~/ondemand/brc_oodapps ^**>  uptime
 13:59:00 up 29 days, 23:40,  4 users,  load average: 257.24, 255.70, 254.47
￼￼
jwhite  2:55 PM
looking at top, I bet you it’s just iodelay running up the load avg, not processor limitation
￼￼
tin￼  2:55 PM
ah, thx John.  I had to join a meeting and haven't really looked into it.
2:55
the io delay is bad though.  rpm takes a long time to come back with result
￼￼
jwhite  2:56 PM
i’ll check if someone’s slamming the nas
2:56
but i mean, rpm on a provisioned machine?
￼￼
tin￼  3:30 PM
not trying to install thing, but it should not take so long to list installed packages.
￼￼
jwhite  3:30 PM
https://grafana.brc.berkeley.edu/d/6435tWeik/ood?from=now-3h&to=now
3:30
it’s a db hosted on nfs, it’s just not efficient
￼￼
tin￼  3:31 PM
grafana link didn't work for me... says not found
￼￼
jwhite  3:31 PM
you need to log in
3:32
Screen Shot 2021-12-08 at 3.31.55 PM.png ￼
￼
￼
￼
3:32
are people complaining or is rpm just taking a long time?
￼￼
tin￼  3:32 PM
ok, iostat on the machine showing not much activity either
3:32
could proxmox be throtleling request?
3:33
i mean, ood file manager app times out waiting
￼￼
jwhite  3:33 PM
no, proxmox is not throttling anything
￼￼
tin￼  3:33 PM
something causing a lot of file io wait... spking uptime, etc
3:33
maybe ood is just pos ￼
￼￼
jwhite  3:33 PM
no, it’s almost certainly nfs just being nfs and the nas being a workhorse
3:33
especially, again, if it’s just you seeing the file manager being slow
￼￼
tin￼  3:34 PM
yeah, df takes forever
3:34
i suspect the nas
3:34
so, maybe we need to find a way to run this server without the nas mount?
￼￼
jwhite  3:34 PM
df should no longer take forever, there was a stale mount on ood i’ve since unmounted
￼￼
tin￼  3:34 PM
it may mean file manager widget would be useless to the users ￼
￼￼
jwhite  3:34 PM
tin, how useful is ood without users homedirs?
￼￼
tin￼  3:35 PM
let me think outloud ￼   can it dispatch jobs to exec host?
￼￼
jwhite  3:36 PM
oh wtf? okay, there is a distinct issue here.  ood is spawning lsof dozens and dozens of times
3:36
that is BAD
3:36
that is horrendous behavior
￼￼
tin￼  3:37 PM
oh, some 500+ times eh?
￼￼
jwhite  3:37 PM
that is… that’s bad coding
￼￼
jwhite  3:46 PM
yea, something is definitely wrong with this.  we may need a reboot to clean up things.  gonna keep poking a bit
3:47
@sn tell me, did i just kill your session?
￼￼
tin￼  3:51 PM
looks like it did
￼￼
jwhite  3:51 PM
damn
3:52
rebooting, sorry
￼￼
tin￼  3:52 PM
might as well ￼
￼￼
jwhite  3:52 PM
i think what happened was I removed /clusterfs/abc without unmounting a week or two ago and by this point, it was just fork-bombing itself w/ lsof runs spawned by logger spawned by crond
￼￼
tin￼  3:53 PM
hmmm....
￼￼
jwhite  3:53 PM
lsof gets REALLY pissed by stale nfs file handles
￼￼
tin￼  3:53 PM
killing those lsof should be ok though ?
￼￼
jwhite  3:53 PM
when i killed lsof, crond/logger just spawned them right back up again and each of the 508 processes was using 2% cpu
3:54
tell me if you can see where i killed the first wave of lsof ￼
Screen Shot 2021-12-08 at 3.54.02 PM.png ￼
￼
￼
￼
3:54
i think nfs is still being slow but it’s a bit hard to track down
￼￼
tin￼  3:56 PM
yeah, the file browser applet is still a bit slow
3:56
but bearable
3:57
thx for fixing this
3:57
hopefully i will soon have time to look at the newer ood 2.x and maybe there are efficiency improvement
￼￼
jwhite  3:58 PM
i’m honestly starting to feel like krishna with this crap
￼￼
tin￼  3:58 PM
maybe i will disable that file manager applet thing -- maybe will live up to my bofh name at least once
￼￼
jwhite  3:58 PM
but yes, this does seem slightly improved
￼￼
tin￼  3:59 PM
dispatched jobs that run on "runner node" behave much better
3:59
just that so many people want a GUI file browser ￼
￼￼
jwhite  3:59 PM
of course
￼￼
paciorek  4:14 PM
Is there an issue we should file with the OOD folks?
￼￼
jwhite  4:14 PM
not ongoing but we did have to reboot ood so running sessions were terminated
￼￼
paciorek  4:15 PM
I meant filing a GitHub issue with the OOD developers...
￼￼
jwhite  4:22 PM
oh, no, not yet
4:22
they do a stupid thing but let’s see if it’s a real issue ongoing

**Comment by tin6150** [comment]
is this still an issue?
We had since then changed the backend storage of the file system storing the OOD binaries and the host should have been much snappier.  
granted user access to their files could still be a problem.  
last time a bunch of lsof was seeking stale FS.  that should no longer be present, but i don;t know if those were the cause of hang.
can someone test and see if the problem persist?

thx!
tin

**Comment by tin6150** [comment]
I restarted the apache service that is responsible for spawning ood sessions.  
My running VScode session remained up.  

**^ tin ood.brc.berkeley.edu ~/CF_BK/ood.brc ^**>  sudo systemctl restart httpd24-httpd.service
Warning: httpd24-httpd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
**^ tin ood.brc.berkeley.edu ~/CF_BK/ood.brc ^**>


I started a new jupyter notebook, 
import numpy
numpy.random.normal(size=120000000)

and eventually got this error:
Kernel Restarting
The kernel appears to have died. It will restart automatically.

This is the same problem you have?  it is likely still limited to 1GB RAM.


The file updated config file
/etc/cgconfig.d/limits.conf
actually resides on the node running jobs (the lha node, currently n0003.testbed0).
this node would need to be restarted.
I am not sure if we can just restart the service, I am not seeing an obvious systemd service named ood-anything.
I think the master ssh to it to start, so I am not sure why it is not reading the updated limit conf.  again it points to needing a whole reboot of n0003.testbed0 for this to be effective.

there are users on it.  I feel like we should just wait till the next scheduled downtime to do this, and check back then.

**Comment by paciorek** [comment]
@tin6150 I'm moving your comment over to the relevant issue so we can keep things organized.

**Comment by tin6150** [comment]
oops sorry, wrote in the wrong window.  
thx for keeping things organized!

**Comment by paciorek** [comment]
Ok, so I checked Files multiple times this week and it has seemed responsive. So I'll close this, hoping the issue is basically resolved.
