### ISSUE TITLE
Issues with Tensorflow Kernels in Jupyter Notebooks

### ISSUE THREAD

**Issue by cthamilton** [ucb-rit/brc_oodapps#17]
We found two issues with the Tensorflow environments for Jupyter notebooks.

Firstly, Tensorflow for python 3.7 version 2.3 is not installed on Savio so the python kernel "Python3.7 TF-2.3.0" leads to a module not found error when trying to import tensorflow.

Secondly, the two working tensorflow kernels "Python3.7 TF-2.1.0" and "Python3.6 TF-1.12" do not work on the nonbatch/debugging node. If you try to import tensorflow in python while using this node, the kernel will instantly fail and have to restart.
(The error for "Python3.7 TF-2.3.0" stays the same.)

Thanks!

**Comment by paciorek** [comment]
@cthamilton Many moons pass... I just tested these out and things seem fine in all regards. I'll close, but feel free to reopen if things still seem awry.
