### ISSUE TITLE
Accessing a web browser via OOD?

### ISSUE THREAD

**Issue by markyashar** [ucb-rit/brc_oodapps#28]
Would it be possible for a user to access a web browser within OOD, i.e., could a web browser app be added to OOD? Is a web browser capability/functionality a part of the new OOD desktop app? In the past, when a user wanted to access a web browser on the Savio cluster, they would be able to access a Firefox browser on the viz node. If the viz node is going to be retired / phased out, would a user be able of access a Firefox or Google Chrome browser within OOD (instead)? Savio users might want to access a web browser to download data or access online data portals, databases, or science gateway portals, etc.

**Comment by paciorek** [comment]
I see that one can open Firefox in the Desktop app. @markyashar can we close this issue?

**Comment by markyashar** [comment]
Yes, please close this issue.
