### ISSUE TITLE
clean up language on app interfaces

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/brc_oodapps#3]
The language on the user interface screens for the various apps could be more clear and has various grammar/punctuation errors. @kmuriki @wfeinstein @nicolaschan is it ok with you if I go through them and make a PR with a bunch of suggestions?

**Comment by wfeinstein** [comment]
Thanks for doing this, great team work. Please make suggestions to improve the clarity of the app interface. More attention was directed to make sure the applications work properly in the first place while developing OOD. Appreciate it for your work and time.

**Comment by paciorek** [comment]
closed via PR #11
