### ISSUE TITLE
have MATLAB and RStudio app interfaces be reactive/contextual like Jupyter app

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/brc_oodapps#4]
The Jupyter app displays the GPU field(s) and number of cores field contextually -- only if the user has chosen a relevant partition. Opening this issue to remind us to port that functionality over to the RStudio and MATLAB apps.

**Comment by kmuriki** [comment]
It should have been working for RStudio if not for me forgetting to push my local branch edits into the main branch which is being pulled into production. Anyways Rstudio should be giving similar contextuality like Jupyter as of today. Please try. @wfeinstein Do you want to fix the Matlab app or should I take crack at that ?

**Comment by paciorek** [comment]
Belatedly noting that RStudio reactivity seems fine to me now.

**Comment by paciorek** [comment]
This is fine now.
