### ISSUE TITLE
rename Python 3 kernel to be "Python 3.7"

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/brc_oodapps#8]
Not strictly an OOD issue, but could we rename the "Python 3" kernel to be "Python 3.7"?

All of our kernels except Python 3.7 have the minor version in their display name, e.g., Python 2.7, Python 3.6, Python 3.7 - TF 2.1.0, etc. So my suggestion is that the display name for the Python 3.7 kernel be "Python 3.7" for consistency and clarity.

**Comment by paciorek** [comment]
@wfeinstein @tin6150 I'd like to bump this. I think making this change would make things much more clear for users. Could one of you do this or get someone else on the LBL team to do so?

**Comment by wfeinstein** [comment]
I will take care of this and will update here

**Comment by wfeinstein** [comment]
python 3 kernel is renamed to python 3.7

**Comment by wfeinstein** [comment]
@paciorek
