### ISSUE TITLE
remove PYTHONPATH from Python 3.6 kernel

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/brc_oodapps#9]
Not strictly an OOD issue, but...

In INC1210051, a user reported a problem with user-installed Python packages in the Python 3.6 kernel not being accessible to him in a notebook. It looks like this is happening because PYTHONPATH is being set in /global/software/sl-7.x86_64/modules/langs/python/3.7/share/jupyter/kernels/python3.6/kernel.json, such that the system path is being put first on sys.path and taking precedence over the user's .local path. Could someone fix this?

**Comment by paciorek** [comment]
@wfeinstein @kmuriki  This issue is coming up for a user in office hours now. Could you or someone on the team fix this soon?

**Comment by wfeinstein** [comment]
I took off PYTHONPATH in the python3.6 kernel. Let me know if this solves users' issue.
